if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/001/CMakeLists.txt)
    add_subdirectory(001)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/002/CMakeLists.txt)
    add_subdirectory(002)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/003/CMakeLists.txt)
    add_subdirectory(003)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/004/CMakeLists.txt)
    add_subdirectory(004)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/005/CMakeLists.txt)
    add_subdirectory(005)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/006/CMakeLists.txt)
    add_subdirectory(006)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/007/CMakeLists.txt)
    add_subdirectory(007)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/008/CMakeLists.txt)
    add_subdirectory(008)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/009/CMakeLists.txt)
    add_subdirectory(009)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/010/CMakeLists.txt)
    add_subdirectory(010)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/011/CMakeLists.txt)
    add_subdirectory(011)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/012/CMakeLists.txt)
    add_subdirectory(012)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/013/CMakeLists.txt)
    add_subdirectory(013)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/014/CMakeLists.txt)
    add_subdirectory(014)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/015/CMakeLists.txt)
    add_subdirectory(015)
endif()
