if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/001/CMakeLists.txt)
    add_subdirectory(001)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/002/CMakeLists.txt)
    add_subdirectory(002)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/003/CMakeLists.txt)
    add_subdirectory(003)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/004/CMakeLists.txt)
    add_subdirectory(004)
endif()

if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/005/CMakeLists.txt)
    add_subdirectory(005)
endif()
