#ifndef CYTRON_MAKER_PI_PICO_BSP_BOARD_H
#define CYTRON_MAKER_PI_PICO_BSP_BOARD_H

#include "boards/cytron_maker_pi_pico.h"

#define BOARD_NAME "Cytron Maker Pi Pico"

#define BOARD_LED_PIN       PICO_DEFAULT_LED_PIN
#define BOARD_UART_ID       PICO_DEFAULT_UART
#define BOARD_UART_TX_PIN   PICO_DEFAULT_UART_TX_PIN
#define BOARD_UART_RX_PIN   PICO_DEFAULT_UART_RX_PIN
#define BOARD_NEOPIXEL_PIN  CYTRON_WS2812_PIN
#define BOARD_BUZZER_PIN    CYTRON_BUZZER_PIN

#define BOARD_BUTTON1_PIN CYTRON_BUTTON1_PIN
#define BOARD_BUTTON2_PIN CYTRON_BUTTON2_PIN
#define BOARD_BUTTON3_PIN CYTRON_BUTTON3_PIN

#define BOARD_AUDIO_LEFT_PIN    CYTRON_AUDIO_LEFT_PIN
#define BOARD_AUDIO_RIGHT_PIN   CYTRON_AUDIO_RIGHT_PIN

#define BOARD_SD_SPI        CYTRON_SD_SPI
#define BOARD_SD_SCK_PIN    CYTRON_SD_SCK_PIN
#define BOARD_SD_MOSI_PIN   CYTRON_SD_MOSI_PIN
#define BOARD_SD_MISO_PIN   CYTRON_SD_MISO_PIN
#define BOARD_SD_CS_PIN     CYTRON_SD_CS_PIN

#define BOARD_ESP_UART      CYTRON_ESP_UART
#define BOARD_ESP_TX_PIN    CYTRON_ESP_TX_PIN
#define BOARD_ESP_RX_PIN    CYTRON_ESP_RX_PIN

#define BOARD_GROVE1_PIN1   CYTRON_GROVE1_PIN1
#define BOARD_GROVE1_PIN2   CYTRON_GROVE1_PIN2
#define BOARD_GROVE2_PIN1   CYTRON_GROVE2_PIN1
#define BOARD_GROVE2_PIN2   CYTRON_GROVE2_PIN2
#define BOARD_GROVE3_PIN1   CYTRON_GROVE3_PIN1
#define BOARD_GROVE3_PIN2   CYTRON_GROVE3_PIN2
#define BOARD_GROVE4_PIN1   CYTRON_GROVE4_PIN1
#define BOARD_GROVE4_PIN2   CYTRON_GROVE4_PIN2
#define BOARD_GROVE5_PIN1   CYTRON_GROVE5_PIN1
#define BOARD_GROVE5_PIN2   CYTRON_GROVE5_PIN2
#define BOARD_GROVE6_PIN1   CYTRON_GROVE6_PIN1
#define BOARD_GROVE6_PIN2   CYTRON_GROVE6_PIN2

#endif
